export interface PropertiesType {
    id: number,
    propertyName: string,
    location: string,
    bedrooms: number,
    bathrooms: number,
    size: number,
    price: number,
    imageUrl: string,
}

export const propertiesData: PropertiesType[] = [
    {
        id: 1,
        propertyName: "Equestrian Family Home",
        location: "New York City, CA, USA",
        bedrooms: 1,
        bathrooms: 2,
        size: 1200,
        price: 45000,
        imageUrl: "/images/properties/p1.jpg",
    },
    {
        id: 2,
        propertyName: "Modern Urban Retreat",
        location: "Brooklyn, NY, USA",
        bedrooms: 2,
        bathrooms: 1,
        size: 950,
        price: 50000,
        imageUrl: "/images/properties/p2.jpg",
    },
    {
        id: 3,
        propertyName: "Cozy Countryside Cottage",
        location: "Albany, NY, USA",
        bedrooms: 3,
        bathrooms: 2,
        size: 1300,
        price: 60000,
        imageUrl: "/images/properties/p3.jpg",
    },
    {
        id: 4,
        propertyName: "Luxury Downtown Apartment",
        location: "Manhattan, NY, USA",
        bedrooms: 1,
        bathrooms: 1,
        size: 800,
        price: 75000,
        imageUrl: "/images/properties/p4.jpg",
    },
    {
        id: 5,
        propertyName: "Spacious Suburban House",
        location: "Staten Island, NY, USA",
        bedrooms: 4,
        bathrooms: 3,
        size: 2000,
        price: 90000,
        imageUrl: "/images/properties/p5.jpg",
    },
    {
        id: 6,
        propertyName: "Chic Studio Loft",
        location: "Queens, NY, USA",
        bedrooms: 1,
        bathrooms: 1,
        size: 700,
        price: 48000,
        imageUrl: "/images/properties/p6.jpg",
    },
];