export const propertiesData = [
    {
        id: 1,
        propertyName: "Equestrian Family Home",
        location: "Əhmədli qəs",
        roomcount: 1,
        floor: 7,
        floorCount: 5,
        area: 1200,
        price: 45000,
        imageUrl: "/images/properties/p1.jpg",
        status: "vip",
        type: "complex",
        rentTime: 1,
        city: "Bakı",
        repair : 1,
        percent: 1,
        doc: 1,
        timeStamp: 1744459118,
    },
    {
        id: 2,
        propertyName: "Modern Urban Retreat",
        location: "Təbriz küç",
        roomcount: 2,
        area: 950,
        price: 50000,
        imageUrl: "/images/properties/p2.jpg",
        status: "premium",
        city: "Bakı",
        repair : 1,
        doc: 1,
        timeStamp: 1744459165,
    },
    {
        id: 3,
        propertyName: "Cozy Countryside Cottage",
        location: "İnşaatçılar m",
        roomcount: 3,
        floor: 9,
        floorCount: 4,
        area: 1300,
        price: 60000,
        imageUrl: "/images/properties/p3.jpg",
        status: "premium",
        type: "agents",
        rentTime: 2,
        city: "Bakı",
        timeStamp: 1649833200000,
    },
    {
        id: 4,
        propertyName: "Luxury Downtown Apartment",
        location: "28 May m",
        roomcount: 1,
        floor: 5,
        floorCount: 5,
        area: 800,
        price: 75000,
        imageUrl: "/images/properties/p4.jpg",
        status: "vip",
        city: "Bakı",
        percent: 1,
        doc: 1,
        timeStamp: 1649833200000,
    },
    {
        id: 5,
        propertyName: "Spacious Suburban House",
        location: "Gəncə pr",
        roomcount: 4,
        price: 90000,
        imageUrl: "/images/properties/p5.jpg",
        type: "complex",
        land: 15,
        rentTime: 1,
        city: "Tovuz",
        repair : 1,
        percent: 1,
        timeStamp: 1743465600,
    },
    {
        id: 6,
        propertyName: "Chic Studio Loft",
        location: "Nəriman Nərimanov m",
        roomcount: 1,
        area: 700,
        price: 48000,
        imageUrl: "/images/properties/p6.jpg",
        status: "vip",
        type: "agents",
        city: "Bakı",
        timeStamp: 1649833200000,
    },
];